### ISSUE TITLE
Publish this somewhere?

### ISSUE THREAD

**Issue by gmethvin** [remithieblin/play-spring-loader#1]
I was trying to make a sample project with Spring and noticed this wasn't published anywhere. It seems to work with Play 2.5.12 and Spring 4.3.5-RELEASE

**Comment by remithieblin** [comment]
I felt it was not ready enough to be published publicly.
It needs a minimum of tests, but i haven't found the time to do so..
But it's easy to build and publish locally.

Glad it works with more recent versions of Play and Spring :)

**Comment by gmethvin** [comment]
The reason I ask is because I'm helping someone upgrade a Play 2.3 project using Spring, so it would be nice to have a public dependency they could use for the application loader. Perhaps you could release as a milestone or RC? It's a fairly complex Spring project so maybe it would also help discover any bugs with this implementation.

**Comment by remithieblin** [comment]
I'm looking into it.
I'll let you know when it's published.
Thanks

**Comment by remithieblin** [comment]
Hi Greg,
It's published in sonatype.
You can add:
"com.actimust"% "play-spring-loader" % "1.0.0" as a dependency, it should find it.
