### ISSUE TITLE
Any plans to push this to one of the artifact stores

### ISSUE THREAD

**Issue by kislayverma** [remithieblin/play-spring-loader#3]
This looks very useful and I am trying to get it to work with my Spring 3.x/4.x based projects. But having to build locally is a bit "un-enterprisey". I'm new to Play, but isn't there a way to publish this as  a plugin somewhere (like the Maven repo)

**Comment by remi-thieblin-ck** [comment]
Hi Kislay, it is published on sonatype:
https://mvnrepository.com/artifact/com.actimust/play-spring-loader/1.0.0
Thanks!

**Comment by kislayverma** [comment]
Oh Brilliant!!!    

So do the "clone and publishlocal" instructions on the README page still stand ? Merely adding the dependency should suffice right?

**Comment by remithieblin** [comment]
Yes, adding the dependency is enough.
Thanks for bringing it up, I updated the README.

**Comment by kislayverma** [comment]
Thanks Remi.
